### ISSUE TITLE
Build failed due to src folder not found on npm release

### ISSUE THREAD

**Issue by paraslamsong** [louaySleman/react-native-launcher-kit#9]
Adding src folder inside the root of the package solved this isse
version: 2.0.0

**Comment by louaySleman** [comment]
@paraslamsong Thanks for the comment I'll fix it on the release as soon as possible.

**Comment by louaySleman** [comment]
Hi @paraslamsong, Could you please check the latest version 2.1.0? The issue should be resolved. 😊

**Comment by numblock** [comment]
Still getting:
```
node:fs:1634
  const stats = binding.lstat(
                        ^
Error: ENOENT: no such file or directory, lstat './node_modules/react-native-launcher-kit/src'
```
on react-native-launcher-kit version 2.1.0.
Node.js v20.17.0

**Comment by louaySleman** [comment]
@numblock, could you share your package.json file, please?

**Comment by numblock** [comment]
```
{
  "name": "devolution",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "lint": "expo lint",
    "release:apk": "cd android && ./gradlew app:assembleRelease",
    "release:bundle": "cd android && ./gradlew app:bundleRelease"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-native-async-storage/async-storage": "^2.1.0",
    "@react-navigation/bottom-tabs": "^7.0.0",
    "@react-navigation/native": "^7.0.0",
    "@react-navigation/native-stack": "^7.1.7",
    "@reduxjs/toolkit": "^2.3.0",
    "expo": "^52.0.9",
    "expo-blur": "^14.0.1",
    "expo-constants": "^17.0.3",
    "expo-dev-client": "^5.0.3",
    "expo-font": "^13.0.1",
    "expo-haptics": "^14.0.0",
    "expo-linking": "^7.0.3",
    "expo-navigation-bar": "^4.0.3",
    "expo-router": "^4.0.7",
    "expo-splash-screen": "^0.29.12",
    "expo-status-bar": "^2.0.0",
    "expo-symbols": "^0.2.0",
    "expo-system-ui": "^4.0.3",
    "expo-web-browser": "^14.0.1",
    "react": "^18.3.1",
    "react-dom": "^18.3.1",
    "react-native": "^0.76.2",
    "react-native-gesture-handler": "^2.20.2",
    "react-native-launcher-kit": "^2.1.0",
    "react-native-reanimated": "^3.16.1",
    "react-native-safe-area-context": "^4.12.0",
    "react-native-screens": "^4.1.0",
    "react-native-web": "^0.19.13",
    "react-native-webview": "^13.12.4",
    "react-redux": "^9.1.2",
    "redux": "^5.0.1",
    "redux-persist": "^6.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/jest": "^29.5.12",
    "@types/react": "^18.3.12",
    "@types/react-test-renderer": "^18.3.0",
    "jest": "^29.2.1",
    "jest-expo": "^52.0.2",
    "react-test-renderer": "^18.3.1",
    "typescript": "^5.3.3"
  },
  "private": true
}
```

I started with the Expo introduction to create a project:
https://docs.expo.dev/get-started/create-a-project/
and continued from there, using a local development build (no EAS).

I get the error when I run `npm run android`. Adding the `src` directory in the node package, as mentioned above, fixes the error and the module works fine.
Now I'm trying to build the project on gitlab-ci and I get the same error, but can't fix it by adding the `src` dir.

**Comment by numblock** [comment]
Changing this line:
https://github.com/louaySleman/react-native-launcher-kit/blob/main/android/build.gradle#L74
 to:
```
jsRootDir = file("../module/")
```
fixes the error for me and the module still works fine.
Not sure if that is the right solution, though. Long-time React developer, but this is my first React-Native project.

**Comment by numblock** [comment]
Looked into it a little more, and looks like there might be something wrong with `release-it`.
If I run `npm pack --dry-run` or `npm publish --dry-run`, the root `src` dir _is_ included in the package, but it seems that it's not when publishing using `release-it`.

**update:**
running `yarn release --dry-run -VV` shows that the `src` dir _is_ added to the tarball. so currently not sure why the `src` dir is not in the published npm package.

**Comment by numblock** [comment]
A workaround that works for me is to point the package to github instead of npm.
In your project's `package.json`, replace
```
"react-native-launcher-kit": "^2.1.0",
```
with
```
"react-native-launcher-kit": "louaySleman/react-native-launcher-kit",
```

**Comment by caghp94** [comment]
any news on this? It's happening after migrating to new arch

**Comment by louaySleman** [comment]
> any news on this? It's happening after migrating to new arch

I'm actively working on a new update to resolve this issue. Stay tuned, and I'll keep you posted once it's ready.

**Comment by arafat-alim-office** [comment]
> A workaround that works for me is to point the package to github instead of npm. In your project's `package.json`, replace
> 
> ```
> "react-native-launcher-kit": "^2.1.0",
> ```
> 
> with
> 
> ```
> "react-native-launcher-kit": "louaySleman/react-native-launcher-kit",
> ```

This tweak helps me to run the application smoothly.
